#!/bin/sh

if [ $# -lt 1 ]
then
	cat <<-tac
		USAGE: $0 <file> [environment]...

		Runs a program in your CPU simulator by launching Logisim in command-line mode.

		<file> may be any memory image or file from which a memory image can be generated.
	tac
	exit 1
fi

file="$1"
if [ ! -e "$file" ]
then
	echo "$file: File not found!" >&2
	exit 2
fi
shift

image="`echo "$file" | sed -e 's/\(\.[^.]*\)$//' -e 's/$/.img/'`"
make "$@" "$image"
status="$?"
if [ "$status" -ne "0" ]
then
	exit "$status"
fi

`make run` "$image"
